config/routes.rb
Upload::Application.routes.draw do
  resources :uploaded_files

end

app/models/uploaded_file.rb
require 'fileutils'

class UploadedFile < ActiveRecord::Base

  after_create :write_file
  before_destroy :prepare_file_for_delete
  after_destroy :delete_file
  
  #set the public dir to create photos dir"
  STORAGE_DIR = "public/"
  
  def inputfile=(input)
    @file_contents = input
    
    self.file_name = input.original_filename
	      
    self.file_type = input.content_type
  end
  
  def inputfile
    self.file_name
  end
  
  def file_path
    t = Time.parse(self.created_at.to_s)
    File.join(UploadedFile::STORAGE_DIR, "#{t.year}/#{t.month}/#{t.day}/")
  end
  
  def contents
    File.open(File.join(self.file_path, self.file_name)).read.to_s
  end
  
  # before_destroy
  def prepare_file_for_delete
    @filename = File.join(self.file_path, self.file_name)
  end
  
  # after_create
  def write_file(data = nil)
    # allow user to provide data
    contents = data || @file_contents.read
    
    # make sure that there is data to write
    if contents
      # filename to use
      filename = self.file_name
	  
      # directory to store it in
      dir = self.file_path
      # create the nested directory to store the file
      FileUtils.mkdir_p dir.to_s 
    
      # write the file
      File.open( File.join(dir, filename), "wb") { |f| f.write(contents) }
	  # update filesize.
	  update_filesize(File.size(File.join(dir, filename)))
	  
    end
  end
  
  def update_filesize(file_size)
  
	helper = Object.new.extend(ActionView::Helpers::NumberHelper)
	numero = helper.number_to_human_size(file_size.to_i,:precision => 2, :separator => ',')
	self.update_attribute("file_size", numero)
	
  end
  
  
  # after_destroy
  def delete_file
    if @filename.nil? || @filename.empty?
      return
    end
    
    file_exists = File.exists?(@filename)
          
    if file_exists
      File.delete(@filename)
    end
  end
  
  private
  
    # santize filenames removing non-alphanumeric 
    def sanitize_filename(filename)
      # IE likes to include the entire path, rather than just the filenam
      just_filename = File.basename(filename) 
    
      # replace all none alphanumeric, underscore or perioids with underscore
      just_filename.sub(/[^\w\.\-]/,'-').downcase
    end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController
  # GET /uploaded_files
  # GET /uploaded_files.xml
  def index
    @uploaded_files = UploadedFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @uploaded_files }
    end
  end

  # GET /uploaded_files/1
  # GET /uploaded_files/1.xml
  def show
    @uploaded_file = UploadedFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @uploaded_file }
    end
  end

  # GET /uploaded_files/new
  # GET /uploaded_files/new.xml
  def new
    @uploaded_file = UploadedFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @uploaded_file }
    end
  end

  # GET /uploaded_files/1/edit
  def edit
    @uploaded_file = UploadedFile.find(params[:id])
  end

  # POST /uploaded_files
  # POST /uploaded_files.xml
  def create
  
    @uploaded_file = UploadedFile.new(params[:uploaded_file])

    respond_to do |format|
      if @uploaded_file.save
        format.html { redirect_to(@uploaded_file, :notice => 'UploadedFile was successfully created.') }
        format.xml  { render :xml => @uploaded_file, :status => :created, :location => @uploaded_file }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @uploaded_file.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /uploaded_files/1
  # PUT /uploaded_files/1.xml
  def update
    @uploaded_file = UploadedFile.find(params[:id])

    respond_to do |format|
      if @uploaded_file.update_attributes(params[:uploaded_file])
        format.html { redirect_to(@uploaded_file, :notice => 'UploadedFile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @uploaded_file.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /uploaded_files/1
  # DELETE /uploaded_files/1.xml
  def destroy
    @uploaded_file = UploadedFile.find(params[:id])
    @uploaded_file.destroy

    respond_to do |format|
      format.html { redirect_to(uploaded_files_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/uploaded_files_helper.rb
module UploadedFilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upload</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/uploaded_files.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>UploadedFiles: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>

	<%= javascript_include_tag 'jquery', 'application' %>
</head>
<body>

<p style="color: green"><%= notice %></p>

<%= yield %>

</body>

<script type="text/javascript">
$(document).ready(function() {
	<%= yield :javascript %>
});
</script>
</html>

app/views/uploaded_files/edit.html.erb
<h1>Editing uploaded_file</h1>

<% form_for(@uploaded_file) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :file_size %><br />
    <%= f.text_field :file_size %>
  </p>
  <p>
    <%= f.label :file_type %><br />
    <%= f.text_field :file_type %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @uploaded_file %> |
<%= link_to 'Back', uploaded_files_path %>

app/views/uploaded_files/index.html.erb
<h1>Listing uploaded_files</h1>

<table>
  <tr>
    <th>File size</th>
    <th>File type</th>
  </tr>

<% @uploaded_files.each do |uploaded_file| %>
  <tr>
    <td><%=h uploaded_file.file_size %></td>
    <td><%=h uploaded_file.file_type %></td>
    <td><%= link_to 'Show', uploaded_file %></td>
    <td><%= link_to 'Edit', edit_uploaded_file_path(uploaded_file) %></td>
    <td><%= link_to 'Destroy', uploaded_file, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New uploaded_file', new_uploaded_file_path %>

app/views/uploaded_files/new.html.erb
<h1>New uploaded_file</h1>

<%= form_for @uploaded_file do |f| %>

  <p>
    <%= f.label :inputfile %><br />
    <%= f.file_field :inputfile %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', uploaded_files_path %>

app/views/uploaded_files/show.html.erb
<p>
  <b>File size:</b>
  <%=h @uploaded_file.file_size %>
</p>

<p>
  <b>File type:</b>
  <%=h @uploaded_file.file_type %>
</p>


<%= link_to 'Edit', edit_uploaded_file_path(@uploaded_file) %> |
<%= link_to 'Back', uploaded_files_path %>